name: Build and Deploy Resume
# Force new deployment
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache TeXLive
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/texlive
            ~/.texlive
          key: ${{ runner.os }}-texlive-${{ hashFiles('Dale_Yarborough_Resume.tex') }}
          restore-keys: |
            ${{ runner.os }}-texlive-

      - name: Install TeXLive
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-latex-base \
            texlive-fonts-recommended \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-extra \
            texlive-pictures \
            texlive-science \
            texlive-bibtex-extra \
            latexmk

      - name: Build Resume
        run: |
          pdflatex -interaction=nonstopmode Dale_Yarborough_Resume.tex
          pdflatex -interaction=nonstopmode Dale_Yarborough_Resume.tex

      - name: Create HTML wrapper
        run: |
          mkdir -p _site
          cp Dale_Yarborough_Resume.pdf _site/
          cp CNAME _site/
          cat > _site/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Dale Yarborough - Resume</title>
              <style>
                  body {
                      margin: 0;
                      padding: 0;
                      height: 100vh;
                      display: flex;
                      flex-direction: column;
                      background-color: #f5f5f5;
                  }
                  iframe {
                      flex: 1;
                      border: none;
                      box-shadow: 0 0 10px rgba(0,0,0,0.1);
                  }
              </style>
          </head>
          <body>
              <iframe src="Dale_Yarborough_Resume.pdf" width="100%" height="100%"></iframe>
          </body>
          </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 