name: Build Resume

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Add permissions to allow pushing commits
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install TeX Live and moderncv
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full texlive-latex-extra
          
      - name: Build Resume
        run: |
          pdflatex -interaction=nonstopmode Dale_Yarborough_Resume.tex
          pdflatex -interaction=nonstopmode Dale_Yarborough_Resume.tex
          
      - name: Commit PDF
        run: |
          git config --local user.email "daleyarborough@gmail.com"
          git config --local user.name "Dale Yarborough"
          git add Dale_Yarborough_Resume.pdf
          git commit -m "Resume Updated" || exit 0
          git push
